DELETE FROM GUARDIAN;
LOAD DATA LOCAL INFILE "/home/szhang73/taskB/GUARDIAN.txt"
INTO TABLE GUARDIAN
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM GUARDIAN
ORDER BY K_ID;
