
LOAD DATA LOCAL INFILE "/home/szhang73/taskB/KID2.txt"
INTO TABLE KID
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA LOCAL INFILE "/home/szhang73/taskB/GUARDIAN.txt"
INTO TABLE GUARDIAN
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA LOCAL INFILE "/home/szhang73/taskB/SCHOOL.txt"
INTO TABLE SCHOOL
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA LOCAL INFILE "/home/szhang73/taskB/POLICE_D.txt"
INTO TABLE POLICEDEPARTMENT
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


LOAD DATA LOCAL INFILE "/home/szhang73/taskB/MISSINS_C.txt"
INTO TABLE MISSINGCASE
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;
